config/routes.rb
Rails.application.routes.draw do
  devise_for :readers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resource :library
  resources :books, constraints: { format: 'json' } do
    collection do
      post :search
      get :reading_list
      get :read_list
    end
  end
  resource :books_readers, only: [:create, :update], constraints: { format: 'json' }
end

app/views/pages/home.html.erb
<!-- <div class="jumbotron">
  <div class="container">
    <h1>BookWorm</h1>
    <p>A simple tool for keepnig track of your reading list.</p>
    <%#= link_to 'Sign Up', new_reader_registration_path, class: 'btn btn-primary btn-lg' %>
  </div>
</div>
 -->

<%= react_component 'react_table/index',
  headers: [
    { display: 'Title', sort: 'title' },
    { display: 'Author', sort: 'author' },
    { display: 'Genre', sort: 'genre' },
    { display: 'Year published', sort: 'year_published' }
  ],
  rows: [
          { title: 'Harry Potter', author: 'J. K. Rowling', genre: 'Fantasy', year_published: 1990 },
          { title: 'Lord of the rings', author: 'J.R.R Tolkien', genre: 'Fantasy', year_published: 1950 },
          { title: 'Eloquent Ruby', author: 'Some guy', genre: 'Learning', year_published: 2003 },
          { title: 'Code: The hidden language' , author: 'Another guy', genre: 'Learning', year_published: 2000},
          { title: 'The Thunderbolt kid', author: 'Bill Bryson', genre: 'Autobiography', year_published: 2010},
          { title: 'Simpsons guide', author: 'Matt Groening', genre: 'Fiction', year_published: 1989},
          { title: 'The Da Vinci Code', author: 'Dan Brown', genre: 'Fiction', year_published: 2001},
          { title: 'Love and Ruin', author: 'Paula McCain', genre: 'Romance', year_published: 2018},
          { title: 'Llama Llama loves to read', author: 'Anna D', genre: 'Children', year_published: 2018},
          { title: 'Old Black Magic', author: 'Ace Atkins', genre: 'Non fiction', year_published: 2018},
          { title: 'Into the Water', author: 'Paula Hawkins', genre: 'Fiction', year_published: 2018}
      ],
  title: 'books'
%>