config/routes.rb
Rails.application.routes.draw do
  devise_for :readers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resource :library
  resources :books, constraints: { format: 'json' } do
    collection do
      post :search
      get :reading_list
      get :read_list
    end
  end
  resource :books_readers, only: [:create, :update], constraints: { format: 'json' }
end

app/views/layouts/_main_nav.html.erb
<div class="navbar navbar-default navbar-inverse-bg">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'BookWorm', root_path, class: 'navbar-brand' %>
    </div>
    <div class="nav navbar-right">
      <% if reader_signed_in? %>
        <%= link_to 'Logout', destroy_reader_session_path, method: :delete, class: 'btn btn-default navbar-btn' %>
      <% else %>
        <%= link_to 'Login', new_reader_session_path, class: 'btn btn-default navbar-btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookWorm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <!-- <p class="notice"><%#= notice %></p>
    <p class="alert"><%#= alert %></p> -->
    <%= render 'layouts/main_nav' %>
    <%= yield %>
  </body>
</html>